Range slider. Phase 0. WIP
wix/stylable-components pull request #280
Opened 2017-09-06 13:05 UTC by Ta4i

For first iteration we need to make it renderable and prepare test base for it.

2017-10-23 13:12 UTC, tyv requested changes

2017-10-24 12:48 UTC, Ta4i commented on demo/components/slider-demo.tsx
> +            value: [50],
Value signature changed for Slider. Both Simple and Range Sliders have array type of value.

2017-10-25 10:52 UTC, Ta4i commented on src/utils/nearest.ts
> +}
Sure. Done

2017-10-25 11:21 UTC, tyv commented on demo/components/slider-demo.tsx
> +            value: [50],
but it is inconvenient

2017-10-25 12:01 UTC, Ta4i commented on demo/components/slider-demo.tsx
> +            value: [50],
Ok, agree. Most frequent case is Simple Slider and it would look strange to use array as value type for it.

2017-10-25 15:11 UTC, merged